/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CAD.UsuariosCAD;
import Config.Bandera;
import Model.Acceso;
import Model.Usuarios;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class vCambiarContra extends javax.swing.JInternalFrame {

    /**
     * Creates new form vCambiarContra
     */
    Acceso Ac;
    public vCambiarContra(Acceso Ac) {
        initComponents();
        this.Ac = Ac;
        vPrincipal.ventana="Cambio Contra";
        LblMensajeNo.setVisible(false);
        LblMensajeSi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtContraActual = new javax.swing.JPasswordField();
        TxtNuevaContra = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        TxtConfirmeContra = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        BtnCambiar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        LblMensajeNo = new javax.swing.JLabel();
        LblMensajeSi = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Titles/CambiarContra.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contraseña actual:");

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nueva Contraseña:");

        TxtContraActual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TxtContraActual.setForeground(new java.awt.Color(255, 0, 0));
        TxtContraActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        TxtNuevaContra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TxtNuevaContra.setForeground(new java.awt.Color(255, 0, 0));
        TxtNuevaContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Confirme nueva contraseña:");

        TxtConfirmeContra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TxtConfirmeContra.setForeground(new java.awt.Color(255, 0, 0));
        TxtConfirmeContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        BtnCambiar.setBackground(new java.awt.Color(255, 153, 0));
        BtnCambiar.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        BtnCambiar.setText("Cambiar");
        BtnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambiarActionPerformed(evt);
            }
        });

        BtnVolver.setBackground(new java.awt.Color(255, 153, 0));
        BtnVolver.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        BtnVolver.setText("Volver");
        BtnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnVolverMouseClicked(evt);
            }
        });
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnCambiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnVolver))
                    .addComponent(jSeparator2)
                    .addComponent(TxtConfirmeContra)
                    .addComponent(TxtContraActual)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtNuevaContra)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtContraActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtNuevaContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtConfirmeContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCambiar)
                    .addComponent(BtnVolver))
                .addContainerGap())
        );

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Titles/Lock.png"))); // NOI18N
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LblMensajeNo.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        LblMensajeNo.setForeground(new java.awt.Color(255, 0, 0));
        LblMensajeNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMensajeNo.setText("La Contrasea NO se pudo cambiar");

        LblMensajeSi.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        LblMensajeSi.setForeground(new java.awt.Color(0, 153, 51));
        LblMensajeSi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMensajeSi.setText("La Contrasea se cambio satisfactoriamente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblMensajeNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblMensajeSi, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblMensajeNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblMensajeSi))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnVolverMouseClicked
        
    }//GEN-LAST:event_BtnVolverMouseClicked

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        //<editor-fold desc="VOLVER" defaultstate="collapsed">
        if (!TxtContraActual.getText().equalsIgnoreCase("") || !TxtNuevaContra.getText().equalsIgnoreCase("") || !TxtConfirmeContra.getText().equalsIgnoreCase("")) {
            int info = JOptionPane.showConfirmDialog(null,"Desea descartar los cambios ?");
            if (info==0) {
                volver();
            }
        }else{
            volver();
        }
        //</editor-fold>
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        vPrincipal.ventana="";
    }//GEN-LAST:event_formInternalFrameClosing

    private void BtnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambiarActionPerformed
        //<editor-fold desc="CAMBIAR CONTRASEÑA" defaultstate="collapsed">
        String Actual = TxtContraActual.getText();
        String Nueva = TxtNuevaContra.getText();
        String Confirmar = TxtConfirmeContra.getText();
        if (!"".equals(Actual)) {
            if (!Confirmar.equals(Nueva)) {
                JOptionPane.showMessageDialog(null,"Las Contraseñas No coinciden\nVerifique de Nuevo");
                TxtNuevaContra.setText("");
                TxtConfirmeContra.setText("");
                TxtNuevaContra.requestFocus();
            }else{
                if ("".equals(Confirmar) && "".equals(Nueva)) {
                    JOptionPane.showMessageDialog(null,"La nueva contraseña debe ser\n de 5 a 20 caracteres");
                }else{
                    Cambiar();
                }
            }
        }else{
            JOptionPane.showMessageDialog(null,"El campo de 'CONTRASEÑA ACTUAL' se encuentra vacio\nPor favor Llenar todos los campos");
            TxtContraActual.requestFocus();
        }
        //</editor-fold>
    }//GEN-LAST:event_BtnCambiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCambiar;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JLabel LblMensajeNo;
    private javax.swing.JLabel LblMensajeSi;
    private javax.swing.JPasswordField TxtConfirmeContra;
    private javax.swing.JPasswordField TxtContraActual;
    private javax.swing.JPasswordField TxtNuevaContra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

    void volver(){
        vPerfil vP = new vPerfil(Ac);        
            vPrincipal.Escritorio.add(vP);            
            Dimension desktopSize = vPrincipal.Escritorio.getSize();
            Dimension FrameSize = vP.getSize();
            vP.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);                    
            vP.toFront();
            vP.setVisible(true);            
            vPrincipal.ventana="Mi Perfil";
            this.dispose();
    }
    
    public void Cambiar(){
        try {
            String Usuario = Bandera.getUsuario();
            String Actual = TxtContraActual.getText();
            String Nueva = TxtNuevaContra.getText();
            
            Usuarios su = new Usuarios();
            su.setUsuario(Usuario);
            su.setContrasena(Actual);
            su.setNuevaContra(Nueva);
            
            boolean acceso = UsuariosCAD.cambiarContrasena(su);
            
            if(!acceso){
                LblMensajeSi.setVisible(false);
                LblMensajeNo.setVisible(true);
                TxtContraActual.setText("");
                TxtNuevaContra.setText("");
                TxtConfirmeContra.setText("");
                TxtContraActual.requestFocus();
            }else{                
                LblMensajeNo.setVisible(false);
                LblMensajeSi.setVisible(true);
                TxtContraActual.setText("");
                TxtNuevaContra.setText("");
                TxtConfirmeContra.setText("");
                TxtContraActual.requestFocus();
            }
        } catch (Exception e) {
            LblMensajeNo.setText(Bandera.getRespuesta());
        }
    }

}
