/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Dimension;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static view.vPrincipal.Escritorio;

/**
 *
 * @author USUARIO
 */
public class vPermisos extends javax.swing.JInternalFrame {

    //<editor-fold desc="PROPIEDADES" defaultstate="collapsed"> 
    public Map getMapPermisos() {
        return mapPermisos;
    }

    public void setMapPermisos(Map mapPermisos) {
        vPermisos.mapPermisos = mapPermisos;
    }

    public void clearMapPermisos() {
        vPermisos.mapPermisos.clear();
    }
    //</editor-fold>

    private static Map mapComponentes = new HashMap();
    private static Map mapPermisos = new HashMap();
    Map infoCampos = new HashMap();

    public vPermisos(Map infoCampos, Map permisosOtorgados) {
        initComponents();
        componenteTabPane();
        this.infoCampos = infoCampos;
        this.mapPermisos = permisosOtorgados;
        verificarCamposRoles(mapPermisos);

    }

    //<editor-fold desc="MAP COMPONENTE TAB_PANE" defaultstate="collapsed"> 
    public void componenteTabPane() {
        for (int i = 0; i < TabPanes.getComponents().length; i++) {
            mapComponentes.put(TabPanes.getComponent(i).getName(), TabPanes.getComponent(i));
        }
        TabPanes.removeAll();
    }
    //</editor-fold>

    //<editor-fold desc="MAP VERIFICAR PERMISOS" defaultstate="collapsed"> 
    public void verificarCamposRoles(Map mapPermisos) {

        if (!mapPermisos.isEmpty()) {
            Iterator entries = mapComponentes.entrySet().iterator();
            while (entries.hasNext()) {
                Map.Entry entry = (Map.Entry) entries.next();
                JPanel oPanel = (JPanel) entry.getValue();
                for (int i = 0; i < oPanel.getComponents().length; i++) {
                    boolean isCheck = oPanel.getComponent(i).getClass() == JCheckBox.class;
                    if (isCheck) {
                        JCheckBox oCheck = (JCheckBox) oPanel.getComponent(i);
                        if (mapPermisos.containsKey(oCheck.getName())) {
                            oCheck.setSelected(true);
                            //continue;
                        }
                        mapPermisos.put(oCheck.getName(), "S");
                    }
                }
            }
        }
    }
    //</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        TabPanes = new javax.swing.JTabbedPane();
        TabPane_Archivo = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        Chk_MiPerfil = new javax.swing.JCheckBox();
        jSeparator18 = new javax.swing.JSeparator();
        TabPane_Movimientos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Chk_CierreSucursal = new javax.swing.JCheckBox();
        jSeparator12 = new javax.swing.JSeparator();
        TabPane_Gestionar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Chk_Platos = new javax.swing.JCheckBox();
        Chk_Productos = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        Chk_Proveedores = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        Chk_Sucursales = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        Chk_Usuarios = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        TabPane_Configuracion = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Chk_Roles = new javax.swing.JCheckBox();
        Chk_Categorias = new javax.swing.JCheckBox();
        Chk_UndMedidas = new javax.swing.JCheckBox();
        Chk_TipoDocumento = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        CbxMenus = new javax.swing.JComboBox<>();
        BtnAceptar = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Titles/AsignarPermisos.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TabPanes.setBackground(new java.awt.Color(255, 255, 255));
        TabPanes.setName("Archivo"); // NOI18N

        TabPane_Archivo.setBackground(new java.awt.Color(255, 255, 255));
        TabPane_Archivo.setToolTipText("");
        TabPane_Archivo.setEnabled(false);
        TabPane_Archivo.setName("Archivo"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Perfil.png"))); // NOI18N
        jLabel18.setText("Mi Perfil :");

        Chk_MiPerfil.setText("Habilitar");
        Chk_MiPerfil.setName("MiPerfil"); // NOI18N

        javax.swing.GroupLayout TabPane_ArchivoLayout = new javax.swing.GroupLayout(TabPane_Archivo);
        TabPane_Archivo.setLayout(TabPane_ArchivoLayout);
        TabPane_ArchivoLayout.setHorizontalGroup(
            TabPane_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPane_ArchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabPane_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator18)
                    .addGroup(TabPane_ArchivoLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(36, 36, 36)
                        .addComponent(Chk_MiPerfil)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        TabPane_ArchivoLayout.setVerticalGroup(
            TabPane_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPane_ArchivoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TabPane_ArchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Chk_MiPerfil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator18, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        TabPanes.addTab("Archivo", TabPane_Archivo);

        TabPane_Movimientos.setBackground(new java.awt.Color(255, 255, 255));
        TabPane_Movimientos.setName("Movimientos"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cierre.png"))); // NOI18N
        jLabel2.setText("Cierre de Sucursal :");

        Chk_CierreSucursal.setText("Habilitar");
        Chk_CierreSucursal.setName("CierreSucursales"); // NOI18N

        javax.swing.GroupLayout TabPane_MovimientosLayout = new javax.swing.GroupLayout(TabPane_Movimientos);
        TabPane_Movimientos.setLayout(TabPane_MovimientosLayout);
        TabPane_MovimientosLayout.setHorizontalGroup(
            TabPane_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPane_MovimientosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabPane_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator12)
                    .addGroup(TabPane_MovimientosLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(Chk_CierreSucursal)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        TabPane_MovimientosLayout.setVerticalGroup(
            TabPane_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPane_MovimientosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TabPane_MovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chk_CierreSucursal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        TabPanes.addTab("Movimientos", TabPane_Movimientos);

        TabPane_Gestionar.setBackground(new java.awt.Color(255, 255, 255));
        TabPane_Gestionar.setName("Gestionar"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Platos.png"))); // NOI18N
        jLabel3.setText("Platos :");

        Chk_Platos.setText("Habilitar");
        Chk_Platos.setName("Platos"); // NOI18N

        Chk_Productos.setText("Habilitar");
        Chk_Productos.setName("Productos"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Productos.png"))); // NOI18N
        jLabel5.setText("Productos :");

        Chk_Proveedores.setText("Habilitar");
        Chk_Proveedores.setName("Proveedores"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Proveedores.png"))); // NOI18N
        jLabel6.setText("Proveedores :");

        Chk_Sucursales.setText("Habilitar");
        Chk_Sucursales.setName("Sucursales"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sucursales.png"))); // NOI18N
        jLabel7.setText("Sucursales :");

        Chk_Usuarios.setText("Habilitar");
        Chk_Usuarios.setName("Usuarios"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Usuarios.png"))); // NOI18N
        jLabel8.setText("Usuarios :");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Informacion.png"))); // NOI18N
        jLabel19.setToolTipText("Modulo en el que puede Gestionar o Registrar  nuevos Datos en el sistema");

        javax.swing.GroupLayout TabPane_GestionarLayout = new javax.swing.GroupLayout(TabPane_Gestionar);
        TabPane_Gestionar.setLayout(TabPane_GestionarLayout);
        TabPane_GestionarLayout.setHorizontalGroup(
            TabPane_GestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPane_GestionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabPane_GestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(TabPane_GestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator11)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabPane_GestionarLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(87, 87, 87)
                            .addComponent(Chk_Platos))
                        .addGroup(TabPane_GestionarLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Chk_Usuarios))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabPane_GestionarLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Chk_Sucursales))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabPane_GestionarLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Chk_Proveedores))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabPane_GestionarLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(67, 67, 67)
                            .addComponent(Chk_Productos))
                        .addComponent(jSeparator7)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        TabPane_GestionarLayout.setVerticalGroup(
            TabPane_GestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPane_GestionarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(TabPane_GestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Chk_Platos))
                .addGap(1, 1, 1)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(TabPane_GestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Chk_Productos))
                .addGap(3, 3, 3)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(TabPane_GestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Chk_Proveedores))
                .addGap(2, 2, 2)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TabPane_GestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Chk_Sucursales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(TabPane_GestionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(Chk_Usuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        TabPanes.addTab("Gestionar", TabPane_Gestionar);

        TabPane_Configuracion.setBackground(new java.awt.Color(255, 255, 255));
        TabPane_Configuracion.setName("Configuración"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/TipoDocumento.png"))); // NOI18N
        jLabel14.setText("Tipo de Documentos :");

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Balanza2.png"))); // NOI18N
        jLabel15.setText("Unidad de Medidas :");

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Categorias.png"))); // NOI18N
        jLabel16.setText("Categorias :");

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Roles.png"))); // NOI18N
        jLabel17.setText("Roles :");

        Chk_Roles.setText("Habilitar");
        Chk_Roles.setName("Roles"); // NOI18N

        Chk_Categorias.setText("Habilitar");
        Chk_Categorias.setName("Categorias"); // NOI18N

        Chk_UndMedidas.setText("Habilitar");
        Chk_UndMedidas.setName("UnidadMedidas"); // NOI18N

        Chk_TipoDocumento.setText("Habilitar");
        Chk_TipoDocumento.setName("TipoDocumentos"); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Informacion.png"))); // NOI18N
        jLabel21.setToolTipText("Modulo en el que puede Configurar Datos del sistema\n");

        javax.swing.GroupLayout TabPane_ConfiguracionLayout = new javax.swing.GroupLayout(TabPane_Configuracion);
        TabPane_Configuracion.setLayout(TabPane_ConfiguracionLayout);
        TabPane_ConfiguracionLayout.setHorizontalGroup(
            TabPane_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabPane_ConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabPane_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TabPane_ConfiguracionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addComponent(jSeparator16, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator15, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator14, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabPane_ConfiguracionLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Chk_Roles))
                    .addGroup(TabPane_ConfiguracionLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Chk_Categorias))
                    .addGroup(TabPane_ConfiguracionLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(Chk_TipoDocumento))
                    .addGroup(TabPane_ConfiguracionLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Chk_UndMedidas)))
                .addGap(27, 27, 27))
        );
        TabPane_ConfiguracionLayout.setVerticalGroup(
            TabPane_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPane_ConfiguracionLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(TabPane_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_TipoDocumento)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(TabPane_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_UndMedidas)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(TabPane_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_Categorias)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(TabPane_ConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chk_Roles)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        TabPanes.addTab("Configuración", TabPane_Configuracion);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel4.setText("Menu :");

        CbxMenus.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        CbxMenus.setForeground(new java.awt.Color(255, 0, 0));
        CbxMenus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Archivo", "Movimientos", "Gestionar", "Configuración" }));
        CbxMenus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbxMenusItemStateChanged(evt);
            }
        });

        BtnAceptar.setBackground(new java.awt.Color(255, 153, 0));
        BtnAceptar.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        BtnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Guardar.png"))); // NOI18N
        BtnAceptar.setToolTipText("Otorgar Permisos");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabPanes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(CbxMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator17))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BtnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(CbxMenus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator17, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabPanes)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        vPrincipal.ventana = "";
    }//GEN-LAST:event_formInternalFrameClosing

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        mapPermisos.clear();
        Iterator entries = mapComponentes.entrySet().iterator();
        while (entries.hasNext()) {
            Map.Entry entry = (Map.Entry) entries.next();
            JPanel oPanel = (JPanel) entry.getValue();
            for (int i = 0; i < oPanel.getComponents().length; i++) {
                boolean isCheck = oPanel.getComponent(i).getClass() == JCheckBox.class;
                if (isCheck) {
                    JCheckBox oCheck = (JCheckBox) oPanel.getComponent(i);
                    if (!oCheck.isSelected()) {
                        continue;
                    }
                    mapPermisos.put(oCheck.getName(), "S");
                }
            }
        }
        vRoles vR = new vRoles();
        if (!vPrincipal.ventana.equalsIgnoreCase("Roles")) {
            vPrincipal.ventana = "Roles";

            Escritorio.add(vR);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vR.getSize();
            vR.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);

            vR.infoCampos.clear();
            vR.infoCampos.put("CamposRoles", this.infoCampos);

            String Id = infoCampos.get("Id").toString();
            String Nombre = infoCampos.get("Nombre").toString();
            String Siglas = infoCampos.get("Siglas").toString();

            vR.Lbl_Id.setText(Id);
            vR.TxtNombre.setText(Nombre);
            vR.TxtSiglas.setText(Siglas);
            ///
            vR.PermisosOtorgados = mapPermisos;
            vR.LblPermisos.setText(Integer.toString(mapPermisos.size()));
            ///
            vR.botonesInicio(false, true, true, true, false, true, false, false, true, true);
            vR.show();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA 'Roles' YA SE ENCUENTRA ABIERTA");

        }
    }//GEN-LAST:event_BtnAceptarActionPerformed

    private void CbxMenusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbxMenusItemStateChanged
        TabPanes.removeAll();
        TabPanes.add((Component) mapComponentes.get(CbxMenus.getSelectedItem()));
    }//GEN-LAST:event_CbxMenusItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JComboBox<String> CbxMenus;
    private javax.swing.JCheckBox Chk_Categorias;
    private javax.swing.JCheckBox Chk_CierreSucursal;
    private javax.swing.JCheckBox Chk_MiPerfil;
    private javax.swing.JCheckBox Chk_Platos;
    private javax.swing.JCheckBox Chk_Productos;
    private javax.swing.JCheckBox Chk_Proveedores;
    private javax.swing.JCheckBox Chk_Roles;
    private javax.swing.JCheckBox Chk_Sucursales;
    private javax.swing.JCheckBox Chk_TipoDocumento;
    private javax.swing.JCheckBox Chk_UndMedidas;
    private javax.swing.JCheckBox Chk_Usuarios;
    private javax.swing.JPanel TabPane_Archivo;
    private javax.swing.JPanel TabPane_Configuracion;
    private javax.swing.JPanel TabPane_Gestionar;
    private javax.swing.JPanel TabPane_Movimientos;
    private javax.swing.JTabbedPane TabPanes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
