/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CAD.CargarCAD;
import Model.Acceso;
import Model.Lista;
import Model.Permisos;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author USUARIO
 */
public class vPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vPrincipal
     */
    static String ventana = "";
    Map mapListaPermisos = new HashMap();
    Acceso Ac;

    public vPrincipal(Acceso Ac, List L) {
        initComponents();
        this.Ac = Ac;
        cargarDatos(Ac);
        PermisosUsuario(L, Ac);
    }

    //<editor-fold desc="IMAGEN DE FONDO" defaultstate="collapsed"> 
    public class ImagenFondo implements Border {

        BufferedImage fondo;

        public ImagenFondo() {
            try {
                //se obtiene la imagen            
                URL url = new URL(getClass().getResource("/img/Titles/Fondo_LogoFood2.png").toString());
                fondo = ImageIO.read(url);

            } catch (IOException ex) {
                Logger.getLogger(ImagenFondo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        // se sobreescriben metodos propios de Border

        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            //se dibuja la imagen de fondo en el centro del contenedor
            //cada que se redimensione el contenedor, la imagen automaticamente se posiciona en el centro
            g.drawImage(fondo, (x + (width - fondo.getWidth()) / 2), (y + (height - fondo.getHeight()) / 2), null);
        }

        public Insets getBorderInsets(Component c) {
            return new Insets(0, 0, 0, 0);
        }

        public boolean isBorderOpaque() {
            return true;
        }
    }
    //</editor-fold>

    //<editor-fold desc="CARGAR DATOS" defaultstate="collapsed"> 
    void cargarDatos(Acceso Ac) {
        Escritorio.setBorder(new ImagenFondo());
        setIconImage(new ImageIcon(getClass().getResource("/img/Titles/IconoLogo.png")).getImage());
        setExtendedState(MAXIMIZED_BOTH);
        LblNombre.setText("Usuario Actual : " + Ac.getNombre() + " " + Ac.getApellido());
        LblNombre.setForeground(Color.BLACK);
        LblRoll.setText(Ac.getNomRoll() + " ( " + Ac.getSiglasRoll() + " )");
    }
    //</editor-fold>

    //<editor-fold desc="PERMISOS USUARIOS" defaultstate="collapsed"> 
    void PermisosUsuario(List Lp, Acceso Ac) {

        JMenuBar barraMenu = getJMenuBar();
        for (int i = 0; i < barraMenu.getMenuCount(); i++) {
            JMenu menu = barraMenu.getMenu(i);

            for (int j = 0; j < menu.getMenuComponentCount(); j++) {
                java.awt.Component oComp = menu.getMenuComponent(j);
                if (oComp instanceof JMenuItem) {
                    JMenuItem menuItem = (JMenuItem) oComp;

                    for (int k = 0; k < Lp.size(); k++) {
                        Permisos Pr = (Permisos) Lp.get(k);
                        String Codigo = Pr.getCodigoPermiso();
                        String Nombre = Pr.getNombrePermiso();

                        if (menuItem.getName().equals(Nombre)) {
                            if (!Codigo.equals("S")) {
                                menuItem.setVisible(false);
                                break;
                            }
                            menuItem.setVisible(true);
                            break;
                        }
                    }// FIn for k
                }// Fin if
            }// Fin for j
        }// Fin for i
    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblNombre = new javax.swing.JLabel();
        LblRoll = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Escritorio = new javax.swing.JDesktopPane();
        MnPrincipal = new javax.swing.JMenuBar();
        MnArchivo = new javax.swing.JMenu();
        MiPerfil = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MnMovimientos = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MnGestiones = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MnConfiguracion = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FoodScrap System V1.0 (easy order)");
        setName("VistaPrincipal"); // NOI18N
        setResizable(false);

        LblNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblNombre.setText("Nombre");

        LblRoll.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LblRoll.setText("Roll");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Escritorio.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        MnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        MnPrincipal.setName("Menu Principal"); // NOI18N

        MnArchivo.setText("Archivo");
        MnArchivo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MnArchivo.setName("Archivo"); // NOI18N
        MnArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MnArchivoMouseReleased(evt);
            }
        });

        MiPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Perfil.png"))); // NOI18N
        MiPerfil.setText("Mi Perfil");
        MiPerfil.setName("MiPerfil"); // NOI18N
        MiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiPerfilActionPerformed(evt);
            }
        });
        MnArchivo.add(MiPerfil);
        MnArchivo.add(jSeparator1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/arrow-top-left-24.png"))); // NOI18N
        jMenuItem2.setText("Cerrar Sesion");
        jMenuItem2.setName("CerrarSesion"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MnArchivo.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reply-24.png"))); // NOI18N
        jMenuItem3.setText("Salir");
        jMenuItem3.setName("Salir"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MnArchivo.add(jMenuItem3);

        MnPrincipal.add(MnArchivo);

        MnMovimientos.setText("Movimientos");
        MnMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MnMovimientos.setName("Movimientos"); // NOI18N

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Cierre.png"))); // NOI18N
        jMenuItem4.setText("Cierre Sucursales");
        jMenuItem4.setName("CierreSucursales"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MnMovimientos.add(jMenuItem4);

        MnPrincipal.add(MnMovimientos);

        MnGestiones.setText("Gestiones");
        MnGestiones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MnGestiones.setName("Gestiones"); // NOI18N

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Platos.png"))); // NOI18N
        jMenuItem7.setText("Platos");
        jMenuItem7.setName("Platos"); // NOI18N
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        MnGestiones.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Productos.png"))); // NOI18N
        jMenuItem8.setText("Productos");
        jMenuItem8.setName("Productos"); // NOI18N
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        MnGestiones.add(jMenuItem8);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Proveedores.png"))); // NOI18N
        jMenuItem10.setText("Proveedores");
        jMenuItem10.setName("Proveedores"); // NOI18N
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        MnGestiones.add(jMenuItem10);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Sucursales.png"))); // NOI18N
        jMenuItem9.setText("Sucursales");
        jMenuItem9.setName("Sucursales"); // NOI18N
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        MnGestiones.add(jMenuItem9);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Usuarios.png"))); // NOI18N
        jMenuItem5.setText("Usuarios");
        jMenuItem5.setName("Usuarios"); // NOI18N
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MnGestiones.add(jMenuItem5);

        MnPrincipal.add(MnGestiones);

        MnConfiguracion.setText("Configuración");
        MnConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MnConfiguracion.setName("Configuracion"); // NOI18N

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/TipoDocumento.png"))); // NOI18N
        jMenuItem15.setText("Tipo Documentos");
        jMenuItem15.setName("TipoDocumentos"); // NOI18N
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        MnConfiguracion.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Balanza2.png"))); // NOI18N
        jMenuItem16.setText("Unidad de Medidas");
        jMenuItem16.setName("UnidadMedidas"); // NOI18N
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        MnConfiguracion.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Categorias.png"))); // NOI18N
        jMenuItem17.setText("Categorias");
        jMenuItem17.setName("Categorias"); // NOI18N
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        MnConfiguracion.add(jMenuItem17);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Roles.png"))); // NOI18N
        jMenuItem18.setText("Roles");
        jMenuItem18.setName("Roles"); // NOI18N
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        MnConfiguracion.add(jMenuItem18);

        MnPrincipal.add(MnConfiguracion);

        setJMenuBar(MnPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(LblRoll, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblRoll)
                    .addComponent(LblNombre))
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //<editor-fold desc="CERRAR SESION" defaultstate="collapsed">
        int Cs = JOptionPane.showConfirmDialog(null, "Desea Cerrar sesion ?", "Cierre de sesion", JOptionPane.YES_NO_OPTION);
        if (Cs == 0) {
            vAcceso vA;
            vA = new view.vAcceso();
            vA.setVisible(true);
            this.dispose();
        } else {
        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //<editor-fold desc="SALIR" defaultstate="collapsed">
        int Alerta = JOptionPane.showConfirmDialog(this, "Desea salir de Sistema ?", "Salir", JOptionPane.YES_NO_OPTION);

        if (Alerta == 0) {
            System.exit(0);
        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiPerfilActionPerformed
        //<editor-fold desc="VER PERFIL" defaultstate="collapsed">
        // Item Perfil
        vPerfil vP = new vPerfil(Ac);
        if (!ventana.equalsIgnoreCase("Mi Perfil") && !ventana.equalsIgnoreCase("Cambio Contra")) {
            ventana = "Mi Perfil";

            Escritorio.add(vP);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vP.getSize();
            vP.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vP.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_MiPerfilActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        //<editor-fold desc="CIERRE SUCURSAL" defaultstate="collapsed">
        // Item Perfil
        vCierreSucursal vS = new vCierreSucursal();
        if (!ventana.equalsIgnoreCase("Cierre Sucursal")) {
            ventana = "Cierre Sucursal";

            Escritorio.add(vS);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vS.getSize();
            vS.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vS.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        //<editor-fold desc="GESTION USUARIOS" defaultstate="collapsed">
        vUsuarios vU = new vUsuarios();
        if (!ventana.equalsIgnoreCase("Gestion Usuarios")) { // && !ventana.equalsIgnoreCase("Cambio Contra")
            ventana = "Gestion Usuarios";

            Escritorio.add(vU);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vU.getSize();
            vU.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vU.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        //<editor-fold desc="GESTION PROVEEDORES" defaultstate="collapsed">
        vProveedores vP = new vProveedores();
        if (!ventana.equalsIgnoreCase("Gestion Proveedores")) { // && !ventana.equalsIgnoreCase("Cambio Contra")
            ventana = "Gestion Proveedores";

            Escritorio.add(vP);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vP.getSize();
            vP.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vP.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        //<editor-fold desc="VER PRODUCTOS" defaultstate="collapsed">
        // Item Perfil
        vProductos vPD = new vProductos();
        if (!ventana.equalsIgnoreCase("Ver Productos")) { // && !ventana.equalsIgnoreCase("Cambio Contra")
            ventana = "Ver Productos";

            Escritorio.add(vPD);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vPD.getSize();
            vPD.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vPD.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        //<editor-fold desc="GESTION SUCURSALES" defaultstate="collapsed">
        vSucursales vS = new vSucursales();
        if (!ventana.equalsIgnoreCase("Gestion Sucursal")) {
            ventana = "Gestion Sucursal";

            Escritorio.add(vS);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vS.getSize();
            vS.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vS.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        //<editor-fold desc="GESTION PLATOS" defaultstate="collapsed">
        vPlatos vPl = new vPlatos();
        if (!ventana.equalsIgnoreCase("Gestion Platos")) {
            ventana = "Gestion Platos";

            Escritorio.add(vPl);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vPl.getSize();
            vPl.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vPl.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        //<editor-fold desc="C TIPO DOCUMENTO" defaultstate="collapsed">
        vTipoDocumento vTd = new vTipoDocumento();
        if (!ventana.equalsIgnoreCase("Config Tipo Documento")) {
            ventana = "Config Tipo Documento";

            Escritorio.add(vTd);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vTd.getSize();
            vTd.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vTd.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        //<editor-fold desc="C UNIDAD MEDIDAS" defaultstate="collapsed">
        vUnidadMedidas vUm = new vUnidadMedidas();
        if (!ventana.equalsIgnoreCase("Config Unidad Medidas")) {
            ventana = "Config Unidad Medidas";

            Escritorio.add(vUm);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vUm.getSize();
            vUm.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vUm.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        //<editor-fold desc="C CATEGORIAS" defaultstate="collapsed">
        vCategorias vCt = new vCategorias();
        if (!ventana.equalsIgnoreCase("Config Categorias")) {
            ventana = "Config Categorias";

            Escritorio.add(vCt);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vCt.getSize();
            vCt.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vCt.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        //<editor-fold desc="C ROLES" defaultstate="collapsed">
        vRoles vRl = new vRoles();
        if (!ventana.equalsIgnoreCase("Config Roles") && !ventana.equalsIgnoreCase("Permisos")) {
            ventana = "Config Roles";

            Escritorio.add(vRl);
            Dimension desktopSize = Escritorio.getSize();
            Dimension FrameSize = vRl.getSize();
            vRl.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vRl.show();
        } else {
            JOptionPane.showMessageDialog(null, "LA VENTANA YA SE ENCUENTRA ABIERTA");

        }
        //</editor-fold>
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void MnArchivoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MnArchivoMouseReleased
//        JOptionPane.showMessageDialog(null, "pacho");
    }//GEN-LAST:event_MnArchivoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new vPrincipal(Ac).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblRoll;
    private javax.swing.JMenuItem MiPerfil;
    private javax.swing.JMenu MnArchivo;
    private javax.swing.JMenu MnConfiguracion;
    private javax.swing.JMenu MnGestiones;
    private javax.swing.JMenu MnMovimientos;
    private javax.swing.JMenuBar MnPrincipal;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
